name: CMake Build ⚒️

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Имя'
        required: true
        default: 'Andrey'
      second_name:
        description: 'Фамилия'
        required: true
        default: 'Harlamow'

env:
  # Здесь можно настроить тип сборки CMake
  BUILD_TYPE: Release

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: CMake Build

    # Для запуска этого приложения используется Github Runner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Временная установка зависимостей
    - name: Install Dependencies
      run: |
        sudo apt-get install \
          libgl1-mesa-dev \
          libx11-dev \
          libxcursor-dev \
          libxi-dev \
          libxinerama-dev \
          libxrandr-dev \
          ninja-build
  
    # Настройка CMake с использованием предустановок
    - name: Configure CMake
      working-directory: cpp
      run: cmake --preset clang-deb-ninja

    # Сборка с использованием предустановок
    - name: Build
      working-directory: cpp
      run: cmake --build --preset clang-deb-ninja

    # Выполнить предварительные тесты
    - name: Test
      working-directory: cpp
      run: ctest --preset clang-deb-ninja
    # Подключение SAST на наш пайплайн
    
